{% set name = "sphinxcontrib-doxylink" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03e871f5833c92f5c1b6f201ca5ab1d9299c12ec749333d3a1c667038baeb050

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - pyparsing >=3.0.8,<4.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - python >=3.7,<4.0
    - sphinx >=1.6

test:
  requires:
    - pip
  imports:
    - sphinxcontrib.doxylink
  commands:
    # check requirements
    - python -m pip check

about:
  home: http://sphinxcontrib-doxylink.readthedocs.io
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for linking to Doxygen documentation.
  doc_url: http://sphinxcontrib-doxylink.readthedocs.io
  dev_url: https://github.com/sphinx-contrib/doxylink

extra:
  recipe-maintainers:
    - duncanmmacleod
    - erykoff
