{% set name = "sphinxcontrib-doxylink" %}
{% set version = "1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6e0c72d607b82de4cba57c6cb53748c8ba0ce0d16d3e3e2384decb8cdc051f9

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools
  run:
    - pyparsing
    - python >=3.4
    - sphinx >=0.6

test:
  imports:
    - sphinxcontrib.doxylink

about:
  home: http://sphinxcontrib-doxylink.readthedocs.io
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for linking to Doxygen documentation.
  doc_url: http://sphinxcontrib-doxylink.readthedocs.io
  dev_url: https://github.com/sphinx-contrib/doxylink

extra:
  recipe-maintainers:
    - duncanmmacleod
    - erykoff
