travis:
  secure:
    BINSTAR_TOKEN: KvXxv3AS9tImo8Q5dYepAEbYPFe4m+ubkugTs48OBgOV7TC3W/VhMRXqbz2MgFU9nL9GyRjq6XFJYI7mI45rsvT6jEO/dm1co6dVQezg68/PZP+QDEtF8DKRoi+YlIBFyTgHfnyR/4UvtCxFPHZA1qtFGG5tnFKttASSpWXzw69hkd2c+Y47wfE9I4cILeswxdFi2/W/r4tFnx86TqlZlERfVJKg1t4a44+2yQS2nMxRZGkzvywm5UkYC+KRsTqOk5cSYm4SAhO5vf4s4yIOGSiUtRBpNr1wHpSWcKGnfnwXERHpW0OKLnDZQ56QB9iUW8F8VykC5MHhUGqJ0OlwRgxgdl///CFXafMsH1VClo3lEi5hoiVfr6ahMH2W/n0eD4hAtUIALkKNvz15jyc6jYn4B4V7KMndXBmtTrzpJZZgx5a6+vWe6y5SWhnnBstA8ag3plE+k5aRfETN1kgidF9JnCGsZBsedGbk7P+3CFNwL5fsu/UYKvLVA/yVj+vmv/I7vYZ0Z4rLkZFnjI4lYci+KjEa+AcpLbT58ZsBnotVe64oLfPji6ntRGM+NN4EmIRhPqz1tiYrw/D2DJnMY7auBMHVxHGjPF2kdknXeXR7bVD4fIjNB+7MuETGF8PmawjRVcz66njJwDsZLyK0Y85E/hJs50Ubmhkpc1iMaUY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
